[book]
authors = ["Narrative Analysis"]
language = "en"
multilingual = true
src = "doc"
title = "Narrative Analysis"

[build]
create-missing = false

[output.html]
edit-url-template = "https://github.com/{org}/{repo}/edit/main/{path}"
git-repository-url = "https://github.com/{org}/{repo}"
git-repository-icon = "fa-github"
